joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.0944  
    has_acceleration_limits: true
    max_acceleration: 2.0944  
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.0944  
    has_acceleration_limits: true
    max_acceleration: 2.0944  
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.1416  
    has_acceleration_limits: true
    max_acceleration: 3.1416  
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.1416  
    has_acceleration_limits: true
    max_acceleration: 3.1416  
  joint_5:
    has_velocity_limits: true
    max_velocity: 3.1416  
    has_acceleration_limits: true
    max_acceleration: 3.1416  
  joint_6:
    has_velocity_limits: true
    max_velocity: 3.1416  
    has_acceleration_limits: true
    max_acceleration: 3.1416  
  joint_7:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -0.03001   
    max_position: 0.00001     
  joint_8:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    min_position: -0.00001     
    max_position: 0.03001    
